sudo: false
language: crystal
notifications:
  email: false
cache:
  directories:
    - $HOME/libsodium
install:
  - if [ ! -d "$HOME/libsodium/lib" ]; then
      wget https://github.com/jedisct1/libsodium/releases/download/1.0.11/libsodium-1.0.11.tar.gz;
      tar xvfz libsodium-1.0.11.tar.gz;
      cd libsodium-1.0.11;
      ./configure --prefix=$HOME/libsodium;
      make;
      make install;
      cd $TRAVIS_BUILD_DIR;
    else
      echo 'Using cached directory.';
    fi
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
